<?php

use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\Core\Field\FieldItemListInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Block\BlockPluginInterface;

/**
 * Implements hook_entity_type_build().
 *
 * @param array $entity_types
 */
function group_gr_roles_entity_type_build(array &$entity_types) {
  // Default group implementation doesn't allow us to set our own role and group
  // content storage controllers or membership loader. Replacing with custom class
  // which is 99% copy but with ability to set custom ones.

  // I don't want to create separate entity type because logically group
  // entity type works perfectly for us, but those small things are not.
  $entity_types['group']->setClass('Drupal\group_gr_roles\Entity\Group');

  // Adding new property to the group type (again, it doesn't make sense to
  // override entire entity type) to handle our settings. This is the wrong
  // way, but this is how it's gonna be until we decide if we go as a
  // submodule or a separate project.
  $current_config_export = $entity_types['group_type']->get('config_export');
  $current_config_export[] = 'roles_inheritance_policy';
  $current_config_export[] = 'group_role_entity_id';
  $current_config_export[] = 'membership_plugin_id';
  $current_config_export[] = 'membership_loader_id';
  $entity_types['group_type']->set('config_export', $current_config_export);

  // We need some more settings on form, so changing form class here.
  $entity_types['group_type']->setFormClass('add', 'Drupal\group_gr_roles\Entity\Form\GroupTypeForm');

  // We need to extend group type functionality to have some more settings accessible
  // from group type entity, so setting out class which is fully based on default one.
  $entity_types['group_type']->setClass('Drupal\group_gr_roles\Entity\GroupType');
}

/**
 * Implements hook_group_content_info_alter().
 *
 * @param $definitions
 */
function group_gr_roles_group_content_info_alter(&$definitions) {
  // We don't want default membership to be enforced because we will give admin
  // to select between our one and default one.
  $definitions['group_membership']['enforced'] = FALSE;
}

/**
 * Implements hook_entity_field_access().
 *
 * @todo Move this to a form controller so we can hide the field if it has no
 *       options available to it?
 */
function group_gr_roles_entity_field_access($operation, FieldDefinitionInterface $field_definition, AccountInterface $account, FieldItemListInterface $items = NULL) {
  // We only care about the group roles field for now.
  if ($field_definition->getName() != 'group_gr_roles') {
    return AccessResult::neutral();
  }

  // Can't retrieve an entity from an empty item list.
  if (!isset($items)) {
    return AccessResult::neutral();
  }

  /** @var \Drupal\group\Entity\GroupContent $group_content */
  $group_content = $items->getEntity();
  $group = $group_content->getGroup();

  // Just to be safe, let's check the plugin ID.
  if ($group_content->getContentPlugin()->getPluginId() == 'group_gr_membership') {
    // Only group administrators should be able to change the membership roles.
    return AccessResult::forbiddenIf(!$group->hasPermission('administer members', $account));
  }

  // Don't show the field if the plugin ID didn't match.
  return AccessResult::forbidden();
}